[Feature] Decrypt update events in the PushNotificationStrategy
wireapp/wire-ios-notification-engine pull request #5
Opened 2020-07-15 19:15 UTC by KaterinaWire

## What's new in this PR?

Decrypt update events in the PushNotificationStrategy

2020-08-26 16:15 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +                //bodyText = "\(localNotifications.count) " + "self.settings.notifications.push_notification.title".localized
Or instead of injecting the strings into the notification engine you could also communicate this to the UI via your delegate with a separate method, something like this:

`createNotification(_ alert: (String, String), showNotification: Bool, bundleCount: Int = 1)`

2020-08-26 16:16 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +            var alert: (String, String) = ("", "")
Let's create a separate struct for this so that it's clear what these strings represent.

2020-08-26 16:18 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    private func didConvert(_ events: [ZMUpdateEvent], liveEvents: Bool, prefetchResult: ZMFetchRequestBatchResult?, moc: NSManagedObjectContext) -> [ZMLocalNotification?] {
This method convert events into ZMLocationNotifications so the `did` prefix doesn't really make sense. Naming something with `did` is mostly used in delegate `protocol` methods.

2020-08-26 16:19 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    private func didConvert(_ events: [ZMUpdateEvent], liveEvents: Bool, prefetchResult: ZMFetchRequestBatchResult?, moc: NSManagedObjectContext) -> [ZMLocalNotification?] {
You can remove the `liveEvents` and `prefetchResult` arguments since they are not used.

2020-08-26 16:21 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +        let eventsToForward = events.filter { $0.source.isOne(of: .pushNotification, .webSocket) }
We don't care about the source in the notification service extension, it's always push notification.

2020-08-26 16:21 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +        eventsToForward.forEach { event in
This could be a `compactMap`

2020-08-26 18:33 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    func shouldCreateNotificationWith(_ alert: (title: String, body: String), showNotification: Bool)
the `should` prefix generally indicate that someone would call this method to find out if it should create a notification or not, but that's not the case here.

Since we are optionally modifying notifications in the notification service extension, maybe something along these lines are more fitting:

`modifyNotification(_ content: Content, showNotification: Bool)`

2020-08-26 18:37 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +public protocol LocalNotificationsDelegate: class {
The name `Local` comes from the fact we were once using [UILocalNotification](https://developer.apple.com/documentation/uikit/uilocalnotification) in order to display notifications, this not the case in notification service extension so I would drop the `Local` prefix or rename it something like `NotificationSessionDelegate`.

2020-08-26 18:43 UTC, typfel requested changes
👍 just some naming which can be improved and made another suggestion about the strings issue we talked about.

2020-08-27 14:53 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    private func didConvert(_ events: [ZMUpdateEvent], liveEvents: Bool, prefetchResult: ZMFetchRequestBatchResult?, moc: NSManagedObjectContext) -> [ZMLocalNotification?] {
Deleted

2020-08-27 14:53 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +        let eventsToForward = events.filter { $0.source.isOne(of: .pushNotification, .webSocket) }
Fixed

2020-08-27 14:53 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +        eventsToForward.forEach { event in
Fixed

2020-08-27 21:42 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +                //bodyText = "\(localNotifications.count) " + "self.settings.notifications.push_notification.title".localized
Done

2020-08-27 21:42 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +            var alert: (String, String) = ("", "")
Done

2020-08-27 21:42 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    private func didConvert(_ events: [ZMUpdateEvent], liveEvents: Bool, prefetchResult: ZMFetchRequestBatchResult?, moc: NSManagedObjectContext) -> [ZMLocalNotification?] {
Fixed

2020-08-27 21:43 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    func shouldCreateNotificationWith(_ alert: (title: String, body: String), showNotification: Bool)
Done

2020-08-27 21:43 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +public protocol LocalNotificationsDelegate: class {
Done

2020-08-28 06:52 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    private func convertToLocalNotifications(_ events: [ZMUpdateEvent], moc: NSManagedObjectContext) -> [ZMLocalNotification?] {
We should be able to return `[ZMLocalNotification]`

2020-08-28 09:28 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +    private func convertToLocalNotifications(_ events: [ZMUpdateEvent], moc: NSManagedObjectContext) -> [ZMLocalNotification?] {
Fixed

2020-09-04 07:42 UTC, typfel commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +            let localNotifications = self.convertToLocalNotifications(decryptedUpdateEvents, moc: self.moc).compactMap { $0 }
`.compactMap { $0 }` is unnecessary now that you don't return an optional array

2020-09-11 06:17 UTC, KaterinaWire commented on Sources/Synchronization/Strategies/PushNotificationStrategy.swift
> +            let localNotifications = self.convertToLocalNotifications(decryptedUpdateEvents, moc: self.moc).compactMap { $0 }
Fixed

2020-09-17 14:09 UTC, merged